apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: "kubedevnews"
          - name: POSTGRES_USER
            value: "kubedevnews"
          - name: POSTGRES_PASSWORD
            value: "Pg#123"
---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector: 
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web
          image: devpolatto/kube-news:latest
          ports:
          - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: ""
          - name: POSTGRES_USERNAME
            value: ""
          - name: POSTGRES_PASSWORD
            value: ""
          - name: DB_HOST
            value: "postgre"
---

apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector: 
    app: web-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer